<a href="https://colab.research.google.com/github/dangvinhhoa06/AI-Thay-Thinh/blob/main/AI_W8_24_03_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install sklearn


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


**Ví dụ 1**

In [ ]:
from sklearn.linear_model import Perceptron

In [ ]:
x= [[0,0],[1,0],[0,1],[1,1]]
y= [0,1,1,1]
model = Perceptron ()
model.fit(x,y)
model.score(x,y)  #Do chinh xac =

1.0

In [ ]:
x1=[[-0.5,-0.5],[10,2],[-1,0.8],[3,5],[1,0.2],[-0.1,0.5]]
y1=model.predict(x1)


In [ ]:
y1

array([0, 1, 0, 1, 1, 0])

In [ ]:
model.score(x1,y1) #==1 la 100%

1.0

Tìm điểm 0.5 0

In [ ]:
y1=model.predict([[0.5,0]])
y1

array([0])

In [ ]:
y1=model.predict([[0,0.5]])
y1

array([0])

Tìm điểm 0.6 0

In [ ]:
y1=model.predict([[0.6,0]])
y1

array([1])

In [ ]:
y1=model.predict([[0,0.6]])
y1

array([1])

In [ ]:
y1=model.predict([[0.51,0]])
y1

array([1])

**Bài khác bài IRIS **

In [ ]:
from sklearn import datasets
from sklearn.linear_model import Perceptron #mô hình
from sklearn.model_selection import train_test_split #Tách tập dữ liệu ra thành 8 2 hoặc 7 3 để không test cái đã train
from sklearn.metrics import accuracy_score 
from sklearn.preprocessing import StandardScaler #chuẩn hóa dữ liệu, ví dụ nhà 1 tỷ, 3000 người thì scale lại cho thành 1 chuẩn, ví dụ từ 0 đến 1

In [ ]:
iris = datasets.load_iris()
x=iris.data
y=iris.target
print(x[:5] )# Select everything up to and including the third element: vector[:3]
print(y[:5])
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)  #= train_test_split(features, target, test_size=0.1, random_state=1)
#0.3 => 30% tỷ lệ 73
sc=StandardScaler()   # ????
sc.fit(x_train)   # ????

x_train_std=sc.transform (x_train) # ????
x_test_std=sc.transform (x_test)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [ ]:
#Học 40 lần: max_iter=40, eta0 tốc độ học, tốc độ lớn ko chính xác, tg học nhanh chạy từ 0 đến 1. random_state lấy ngẫu nhiên dữ liệu
model = Perceptron(max_iter=40, eta0=0.1, random_state=0)  
model.fit(x_train_std, y_train) #lấy dữ liệu đã scale rồi
y_pred=model.predict(x_test_std)
#Đang so sánh 2 cái pred với thực
print(y_pred)
print(y_test)
print("Độ chính xác của mô hình: ", accuracy_score(y_test, y_pred))  #So sánh độ chính xác của test. Học luôn cao hơn test

[0 2 1 2 2 0 0 2 0 1 2 0 1 1 0 2 1 0 2 1 1 1 1 0 1 0 1 0 1 0 2 0 2 0 0 1 1
 1 2 1 1 0 2 1 2]
[0 2 1 2 2 0 0 2 0 1 2 0 1 1 0 2 1 0 2 1 1 2 1 0 1 0 2 0 1 0 2 0 1 0 0 1 1
 2 2 1 1 0 2 1 2]
Độ chính xác của mô hình:  0.9111111111111111


**Bài crabs**

In [ ]:
import matplotlib.pyplot as plt
from sklearn import datasets
import pandas as pd
import numpy as np
from sklearn.linear_model import Perceptron #mô hình
from sklearn.model_selection import train_test_split #Tách tập dữ liệu ra thành 8 2 hoặc 7 3 để không test cái đã train
from sklearn.metrics import accuracy_score 
from sklearn.preprocessing import StandardScaler #chuẩn hóa dữ liệu, ví dụ nhà 1 tỷ, 3000 người thì scale lại cho thành 1 chuẩn, ví dụ từ 0 đến 1
url ='crabs.csv'
dataframe = pd.read_csv(url)
dataframe.head(100) #Hiện 10 thằng đầu tiên

speies=dataframe['speies'].replace(["O", "B"], [1, 0]).head(20)
sex=dataframe['sex'].replace(["M", "F"], [1, 0]).head(20)
#Chuyển bằng replace, đổi O thành 1, B thành 0. 
#Male thành 1, Female thành 0. Loài là input, output là giới tính đực hay cái, đám sau là input
#7 tín hiệu vào, 1 tín hiệu ra là giới tính
